FROM node:20-alpine AS deps

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm ci


FROM node:20-alpine AS builder

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY . .

ARG TWITCH_CLIENT_ID
ARG TWITCH_CLIENT_SECRET
ARG KICK_CLIENT_ID
ARG KICK_CLIENT_SECRET
ARG KICK_REDIRECT_URI
ARG KICK_API_URL
ARG YOUTUBE_API_KEY
ARG SUPABASE_URL
ARG SUPABASE_PUBLISHABLE_KEY
ARG SUPABASE_SECRET_KEY
ARG SUPABASE_JWKS_URL
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ARG TIKTOK_WORKER_URL
ARG TIKTOK_WORKER_SECRET
ARG DATABASE_URL
ARG DATABASE_SSL
ARG GIT_SHA

ENV TWITCH_CLIENT_ID=$TWITCH_CLIENT_ID
ENV TWITCH_CLIENT_SECRET=$TWITCH_CLIENT_SECRET
ENV KICK_CLIENT_ID=$KICK_CLIENT_ID
ENV KICK_CLIENT_SECRET=$KICK_CLIENT_SECRET
ENV KICK_REDIRECT_URI=$KICK_REDIRECT_URI
ENV KICK_API_URL=$KICK_API_URL
ENV YOUTUBE_API_KEY=$YOUTUBE_API_KEY
ENV SUPABASE_URL=$SUPABASE_URL
ENV SUPABASE_PUBLISHABLE_KEY=$SUPABASE_PUBLISHABLE_KEY
ENV SUPABASE_SECRET_KEY=$SUPABASE_SECRET_KEY
ENV SUPABASE_JWKS_URL=$SUPABASE_JWKS_URL
ENV NEXT_PUBLIC_SUPABASE_URL=$NEXT_PUBLIC_SUPABASE_URL
ENV NEXT_PUBLIC_SUPABASE_ANON_KEY=$NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV TIKTOK_WORKER_URL=$TIKTOK_WORKER_URL
ENV TIKTOK_WORKER_SECRET=$TIKTOK_WORKER_SECRET
ENV DATABASE_URL=$DATABASE_URL
ENV DATABASE_SSL=$DATABASE_SSL
ENV GIT_SHA=$GIT_SHA
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build


FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=80
ENV HOSTNAME=0.0.0.0

RUN apk add --no-cache postgresql-client \
    && addgroup --system --gid 1001 nodejs \
    && adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public
COPY --from=builder /app/postgres ./postgres

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

COPY --chown=nextjs:nodejs docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

USER nextjs

EXPOSE 80

ENTRYPOINT ["/usr/local/bin/docker-entrypoint.sh"]
CMD ["node", "server.js"]
